name: Docker Image CI

on:
  pull_request:
    branches: ["master"]

env:
  TARGETS: "default"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          set -eEuo pipefail
          for t in $TARGETS; do
            docker build . --file Dockerfile --target="$t"
          done
